/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: ROS_Pose.h
  Source: /home/joonas/repos/personal/DDS-Doom/doomgeneric/ROS_Pose.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ROS_POSE_H
#define DDSC_ROS_POSE_H

#include "ROS_Point.h"

#include "ROS_Quaternion.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_dds__Pose_
{
  struct geometry_msgs_msg_dds__Point_ position;
  struct geometry_msgs_msg_dds__Quaternion_ orientation;
} geometry_msgs_msg_dds__Pose_;

extern const dds_topic_descriptor_t geometry_msgs_msg_dds__Pose__desc;

#define geometry_msgs_msg_dds__Pose___alloc() \
((geometry_msgs_msg_dds__Pose_*) dds_alloc (sizeof (geometry_msgs_msg_dds__Pose_)));

#define geometry_msgs_msg_dds__Pose__free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_dds__Pose__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROS_POSE_H */
