/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: ROS_Image_shm.h
  Source: /home/joonas/repos/personal/DDS-Doom/doomgeneric/ROS_Image_shm.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ROS_IMAGE_SHM_H
#define DDSC_ROS_IMAGE_SHM_H

#include "ROS_Header.h"

#include "ROS_Shm.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sensor_msgs_msg_dds__Image_shm_
{
  struct std_msgs_msg_dds__Header_ header;
  uint32_t height;
  uint32_t width;
  char * encoding;
  uint8_t is_bigendian;
  uint32_t step;
  struct std_msgs_msg_dds__Shm_ data;
} sensor_msgs_msg_dds__Image_shm_;

extern const dds_topic_descriptor_t sensor_msgs_msg_dds__Image_shm__desc;

#define sensor_msgs_msg_dds__Image_shm___alloc() \
((sensor_msgs_msg_dds__Image_shm_*) dds_alloc (sizeof (sensor_msgs_msg_dds__Image_shm_)));

#define sensor_msgs_msg_dds__Image_shm__free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_dds__Image_shm__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROS_IMAGE_SHM_H */
