/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: ROS_PoseArray.h
  Source: /home/joonas/repos/personal/DDS-Doom/doomgeneric/ROS_PoseArray.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ROS_POSEARRAY_H
#define DDSC_ROS_POSEARRAY_H

#include "ROS_Pose.h"

#include "ROS_Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_GEOMETRY_MSGS_MSG_DDS__POSE__DEFINED
#define DDS_SEQUENCE_GEOMETRY_MSGS_MSG_DDS__POSE__DEFINED
typedef struct dds_sequence_geometry_msgs_msg_dds__Pose_
{
  uint32_t _maximum;
  uint32_t _length;
  struct geometry_msgs_msg_dds__Pose_ *_buffer;
  bool _release;
} dds_sequence_geometry_msgs_msg_dds__Pose_;

#define dds_sequence_geometry_msgs_msg_dds__Pose___alloc() \
((dds_sequence_geometry_msgs_msg_dds__Pose_*) dds_alloc (sizeof (dds_sequence_geometry_msgs_msg_dds__Pose_)));

#define dds_sequence_geometry_msgs_msg_dds__Pose__allocbuf(l) \
((struct geometry_msgs_msg_dds__Pose_ *) dds_alloc ((l) * sizeof (struct geometry_msgs_msg_dds__Pose_)))
#endif /* DDS_SEQUENCE_GEOMETRY_MSGS_MSG_DDS__POSE__DEFINED */

typedef struct geometry_msgs_msg_dds__PoseArray_
{
  struct std_msgs_msg_dds__Header_ header;
  dds_sequence_geometry_msgs_msg_dds__Pose_ poses;
} geometry_msgs_msg_dds__PoseArray_;

extern const dds_topic_descriptor_t geometry_msgs_msg_dds__PoseArray__desc;

#define geometry_msgs_msg_dds__PoseArray___alloc() \
((geometry_msgs_msg_dds__PoseArray_*) dds_alloc (sizeof (geometry_msgs_msg_dds__PoseArray_)));

#define geometry_msgs_msg_dds__PoseArray__free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_dds__PoseArray__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROS_POSEARRAY_H */
