/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: ROS_GamePad.h
  Source: /home/joonas/repos/personal/DDS-Doom/doomgeneric/ROS_GamePad.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ROS_GAMEPAD_H
#define DDSC_ROS_GAMEPAD_H

#include "ROS_Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sensor_msgs_msg_GamePad
{
  struct std_msgs_msg_dds__Header_ header;
  float LS_X;
  float LS_Y;
  float RS_X;
  float RS_Y;
  float LT;
  float RT;
  bool start;
  bool select;
  bool x;
  bool y;
  bool a;
  bool b;
  bool dpad_up;
  bool dpad_down;
  bool dpad_left;
  bool dpad_right;
  bool LB;
  bool RB;
  bool LS;
  bool RS;
} sensor_msgs_msg_GamePad;

extern const dds_topic_descriptor_t sensor_msgs_msg_GamePad_desc;

#define sensor_msgs_msg_GamePad__alloc() \
((sensor_msgs_msg_GamePad*) dds_alloc (sizeof (sensor_msgs_msg_GamePad)));

#define sensor_msgs_msg_GamePad_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_GamePad_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROS_GAMEPAD_H */
