/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: ROS_Time.h
  Source: /home/joonas/repos/personal/DDS-Doom/doomgeneric/ROS_Time.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ROS_TIME_H
#define DDSC_ROS_TIME_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct std_msgs_msg_dds__Time_
{
  int32_t sec;
  uint32_t nanosec;
} std_msgs_msg_dds__Time_;

extern const dds_topic_descriptor_t std_msgs_msg_dds__Time__desc;

#define std_msgs_msg_dds__Time___alloc() \
((std_msgs_msg_dds__Time_*) dds_alloc (sizeof (std_msgs_msg_dds__Time_)));

#define std_msgs_msg_dds__Time__free(d,o) \
dds_sample_free ((d), &std_msgs_msg_dds__Time__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROS_TIME_H */
