/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: ROS_Quaternion.h
  Source: /home/joonas/repos/personal/DDS-Doom/doomgeneric/ROS_Quaternion.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ROS_QUATERNION_H
#define DDSC_ROS_QUATERNION_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_dds__Quaternion_
{
  double x;
  double y;
  double z;
  double w;
} geometry_msgs_msg_dds__Quaternion_;

extern const dds_topic_descriptor_t geometry_msgs_msg_dds__Quaternion__desc;

#define geometry_msgs_msg_dds__Quaternion___alloc() \
((geometry_msgs_msg_dds__Quaternion_*) dds_alloc (sizeof (geometry_msgs_msg_dds__Quaternion_)));

#define geometry_msgs_msg_dds__Quaternion__free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_dds__Quaternion__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROS_QUATERNION_H */
