/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: ROS_Image.h
  Source: /home/joonas/repos/personal/DDS-Doom/doomgeneric/ROS_Image.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ROS_IMAGE_H
#define DDSC_ROS_IMAGE_H

#include "ROS_Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() \
((dds_sequence_octet*) dds_alloc (sizeof (dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

typedef struct sensor_msgs_msg_dds__Image_
{
  struct std_msgs_msg_dds__Header_ header;
  uint32_t height;
  uint32_t width;
  char * encoding;
  uint8_t is_bigendian;
  uint32_t step;
  dds_sequence_octet data;
} sensor_msgs_msg_dds__Image_;

extern const dds_topic_descriptor_t sensor_msgs_msg_dds__Image__desc;

#define sensor_msgs_msg_dds__Image___alloc() \
((sensor_msgs_msg_dds__Image_*) dds_alloc (sizeof (sensor_msgs_msg_dds__Image_)));

#define sensor_msgs_msg_dds__Image__free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_dds__Image__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROS_IMAGE_H */
