/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: ROS_Point.h
  Source: /home/joonas/repos/personal/DDS-Doom/doomgeneric/ROS_Point.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ROS_POINT_H
#define DDSC_ROS_POINT_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_dds__Point_
{
  double x;
  double y;
  double z;
} geometry_msgs_msg_dds__Point_;

extern const dds_topic_descriptor_t geometry_msgs_msg_dds__Point__desc;

#define geometry_msgs_msg_dds__Point___alloc() \
((geometry_msgs_msg_dds__Point_*) dds_alloc (sizeof (geometry_msgs_msg_dds__Point_)));

#define geometry_msgs_msg_dds__Point__free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_dds__Point__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROS_POINT_H */
