/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: ROS_Shm.h
  Source: /home/joonas/repos/personal/DDS-Doom/doomgeneric/ROS_Shm.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ROS_SHM_H
#define DDSC_ROS_SHM_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct std_msgs_msg_dds__Shm_
{
  uint32_t size;
  char * name;
} std_msgs_msg_dds__Shm_;

extern const dds_topic_descriptor_t std_msgs_msg_dds__Shm__desc;

#define std_msgs_msg_dds__Shm___alloc() \
((std_msgs_msg_dds__Shm_*) dds_alloc (sizeof (std_msgs_msg_dds__Shm_)));

#define std_msgs_msg_dds__Shm__free(d,o) \
dds_sample_free ((d), &std_msgs_msg_dds__Shm__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROS_SHM_H */
